### ISSUE TITLE
Support for cordova-android >= v7

### ISSUE THREAD

**Issue by pcsantana** [apache/cordova-plugin-globalization#71] opened 2018-12-29 14:00 UTC
Hi, thanks for this plugin!

It looks like the plugin isn't compatible with cordova-android 7.x
During the installation, the following error throws:

> Failed to install 'cordova-plugin-globalization': Error: ENOENT: no such file or directory, open '<path_project>/platforms/android/AndroidManifest.xml'
....

**Comment by jcesarmobile** [comment] 2019-09-11 11:19
That's usually caused by another plugin, but cordova wrongly points to the next plugin installed instead of to the failing one. Most of the plugin problems were fixed in latest version of v7 and are also fixed on v8, so make sure you are using latest version.

**Closed by jcesarmobile** 2019-09-11 11:19 UTC
Labels: platform: android, support
